### ISSUE TITLE
PyPI package is outdated

### ISSUE THREAD

**Issue by diogocp** [open-iscsi/configshell-fb#41]
The latest version on PyPI is still 1.1.23.
https://pypi.python.org/pypi/configshell-fb

**Comment by agrover** [comment]
I don't own the configshell-fb package on pypi,  "iavael" does, so you'll need to contact them to get it updated.

(I initially did not publish configshell-fb on pypi like I did rtslib-fb, so I guess iavael stepped in. If everything is unmodified I should say thanks? I'd feel better if I knew a little more about this person, though.)

**Comment by diogocp** [comment]
@iavael, is that you?

**Comment by iavael** [comment]
@diogocp yep, it's me. Code was uploaded "as is" from tag in this repo, but I actually don't track new release, that's why it's outdated.

**Comment by iavael** [comment]
@agrover looks like it's possible to transfer package ownership in pypi via https://sourceforge.net/p/pypi/support-requests/, so I can give package ownership to you, if you want to get it.
If you prefer not to have this package in pypi at all, I can delete project from it.

**Comment by diogocp** [comment]
@iavael since you already own the package, you don't need to open a support request to transfer ownership. See the instructions here: https://stackoverflow.com/a/23362484/554039

**Comment by iavael** [comment]
@diogocp 
Oh, really. Thx for advice.

@agrover 
So then, if you write preferred pypi account name here, I would set it as owner of this package (and remove ownership from myself)

**Comment by iavael** [comment]
@agrover 

For now I've added "agrover" account from rtslib-fb as owner (since there were releases of rtslib-fb recently, looks like this account is valid and used). Confirm if you've gained access and i'll delete myself from owners.

**Comment by agrover** [comment]
hi @iavael seems good here. I tested by uploading 1.1.24, no issues.

Much thanks to both of you!

**Comment by iavael** [comment]
@agrover OK, removed myself from package owners
