### ISSUE TITLE
Forgot to tag version 1.1.27?

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/configshell-fb#55]
Hi: I believe you may have forgotten to push you git tag for v1.1.27. You have one for 1.1.26, and you set up a github release for 1.1.27. I'm guessing you created a tag and forgot to do a "git push --tags"?

I'm not sure it matters much, but for consistency, can you tag it? I could submit a pull request, if you wish, but it's a simple change.

**Comment by maurizio-lombardi** [comment]
Hello, you are right, I will tag it

**Comment by maurizio-lombardi** [comment]
Should be fixed now

**Comment by gonzoleeman** [comment]
Thank you!
